[package]
name = "ragnarok-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
ragnarok-game = { workspace = true }
ragnarok-renderer = { workspace = true }
ragnarok-formats = { workspace = true }
models = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
