//! Stable identifier for every visual effect the client can spawn.
//!
//! This is a hand-curated representative sample. The full enum (~1000
//! variants matching the original's `EF_*` constants in `effects-enum.txt`) will be
//! generated by `tools/gen_effect_table` once that's built.
//!
//! Discriminants match reference `EF_*` values so we can round-trip with any
//! existing data table without a remapping layer.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum EffectId {
    // Ambient / map
    Torch = 45,
    ChimneySmoke = 44,
    Bubble = 109,
    GasPush = 110,
    Spring = 111,

    // Hit / damage
    Hit1 = 0,
    Hit2 = 1,
    Hit3 = 2,

    // Skill — first-class examples chosen for their architectural variety
    FireBolt = 17,
    ColdBolt = 18,
    LightningBolt = 19,
    IceWall = 27,
    EarthSpike = 56,
    GrimTooth = 75,
    MagnusExorcismus = 76,
    GrandCross = 88,
    LordOfVermillion = 51,
    StormGust = 89,

    // Status / persistent
    Level99 = 149,
    Lvup = 150,
    JobLvup = 151,
    RefineOk = 152,
    RefineFail = 153,

    // Consumables
    Potion1 = 181,
    Potion2 = 182,
}

impl EffectId {
    pub fn as_u16(self) -> u16 {
        self as u16
    }
}
