// Pet illustration + accessory-ACT tables (ported from the original client).
// The paths are the exact GRF resource names; missing files fall back at the
// call site (plain mob ACT / Poring illustration).

/// Poring illustration, used when a pet has no dedicated illustration entry.
pub const PET_ILLUST_FALLBACK: &str = "data/texture/유저인터페이스/illust/펫_포링.bmp";

pub fn pet_illust(mob_id: i16) -> Option<&'static str> {
    match mob_id {
        1002 => Some("data/texture/유저인터페이스/illust/펫_포링.bmp"),
        1011 => Some("data/texture/유저인터페이스/illust/펫_촌촌.bmp"),
        1014 => Some("data/texture/유저인터페이스/illust/펫_스포아.bmp"),
        1019 => Some("data/texture/유저인터페이스/illust/펫_페코페코.bmp"),
        1023 => Some("data/texture/유저인터페이스/illust/펫_오크워리어.bmp"),
        1026 => Some("data/texture/유저인터페이스/illust/펫_무낙.bmp"),
        1029 => Some("data/texture/유저인터페이스/illust/펫_이시스.bmp"),
        1031 => Some("data/texture/유저인터페이스/illust/펫_포포링.bmp"),
        1035 => Some("data/texture/유저인터페이스/illust/펫_헌터플라이.bmp"),
        1040 => Some("data/texture/유저인터페이스/illust/펫_GOLEM.bmp"),
        1042 => Some("data/texture/유저인터페이스/illust/펫_스틸촌촌.bmp"),
        1049 => Some("data/texture/유저인터페이스/illust/펫_픽키.bmp"),
        1052 => Some("data/texture/유저인터페이스/illust/펫_로커.bmp"),
        1056 => Some("data/texture/유저인터페이스/illust/펫_스모키.bmp"),
        1057 => Some("data/texture/유저인터페이스/illust/펫_요요.bmp"),
        1063 => Some("data/texture/유저인터페이스/illust/펫_루나틱.bmp"),
        1077 => Some("data/texture/유저인터페이스/illust/펫_포이즌스포아.bmp"),
        1101 => Some("data/texture/유저인터페이스/illust/펫_바포메트.bmp"),
        1107 => Some("data/texture/유저인터페이스/illust/펫_데져트울프새끼.bmp"),
        1109 => Some("data/texture/유저인터페이스/illust/펫_데비루치.bmp"),
        1110 => Some("data/texture/유저인터페이스/illust/펫_도깨비.bmp"),
        1113 => Some("data/texture/유저인터페이스/illust/펫_드롭프스.bmp"),
        1122 => Some("data/texture/유저인터페이스/illust/펫_고블린_단검.bmp"),
        1123 => Some("data/texture/유저인터페이스/illust/펫_고블린_플레일.bmp"),
        1125 => Some("data/texture/유저인터페이스/illust/펫_고블린_해머.bmp"),
        1143 => Some("data/texture/유저인터페이스/illust/펫_MARIONETTE.bmp"),
        1148 => Some("data/texture/유저인터페이스/illust/펫_MEDUSA.bmp"),
        1155 => Some("data/texture/유저인터페이스/illust/펫_쁘띠.bmp"),
        1167 => Some("data/texture/유저인터페이스/illust/펫_세비지베베.bmp"),
        1170 => Some("data/texture/유저인터페이스/illust/펫_소희.bmp"),
        1179 => Some("data/texture/유저인터페이스/illust/펫_WHISPER.BMP"),
        1188 => Some("data/texture/유저인터페이스/illust/펫_본건.bmp"),
        1200 => Some("data/texture/유저인터페이스/illust/펫_ZHERLTHSH.bmp"),
        1208 => Some("data/texture/유저인터페이스/illust/펫_배회하는자.bmp"),
        1245 => Some("data/texture/유저인터페이스/illust/펫_고블린_이벤트.bmp"),
        1275 => Some("data/texture/유저인터페이스/illust/펫_ALICE.bmp"),
        1299 => Some("data/texture/유저인터페이스/illust/펫_GOBLIN_LEADER.bmp"),
        1370 => Some("data/texture/유저인터페이스/illust/펫_SUCCUBUS.bmp"),
        1374 => Some("data/texture/유저인터페이스/illust/펫_INCUBUS.bmp"),
        1379 => Some("data/texture/유저인터페이스/illust/펫_NIGHTMARE_TERROR.bmp"),
        1382 => Some("data/texture/유저인터페이스/illust/펫_디아볼릭.bmp"),
        1385 => Some("data/texture/유저인터페이스/illust/펫_지상딜리터.bmp"),
        1401 => Some("data/texture/유저인터페이스/illust/펫_SHINOBI.bmp"),
        1404 => Some("data/texture/유저인터페이스/illust/펫_MIYABI_NINGYO.bmp"),
        1416 => Some("data/texture/유저인터페이스/illust/펫_WICKED_NYMPH.bmp"),
        1495 => Some("data/texture/유저인터페이스/illust/펫_STONE_SHOOTER.bmp"),
        1504 => Some("data/texture/유저인터페이스/illust/펫_DULLAHAN.bmp"),
        1505 => Some("data/texture/유저인터페이스/illust/펫_LOLI_RURI.BMP"),
        1513 => Some("data/texture/유저인터페이스/illust/펫_CIVIL_SERVANT.bmp"),
        1519 => Some("data/texture/유저인터페이스/illust/펫_청이.bmp"),
        1586 => Some("data/texture/유저인터페이스/illust/펫_LEAF_CAT.bmp"),
        1630 => Some("data/texture/유저인터페이스/illust/펫_BACSOJIN.bmp"),
        1815 => Some("data/texture/유저인터페이스/illust/펫_떡_이벤트.bmp"),
        1837 => Some("data/texture/유저인터페이스/illust/펫_IMP.bmp"),
        1879 => Some("data/texture/유저인터페이스/illust/펫_루나틱.bmp"),
        1963 => Some("data/texture/유저인터페이스/illust/펫_청이.bmp"),
        2200 => Some("data/texture/유저인터페이스/illust/펫_j_taini.bmp"),
        2210 => Some("data/texture/유저인터페이스/illust/펫_크리스마스_눈토끼.bmp"),
        _ => None,
    }
}

pub fn pet_accessory_act(view_id: u16) -> Option<&'static str> {
    match view_id {
        10001 => Some("data/sprite/몬스터/BAPHOMET_뼉다구모자.act"),
        10002 => Some("data/sprite/몬스터/chocho_방독면.act"),
        10003 => Some("data/sprite/몬스터/DESERT_WOLF_B_우주복머리.act"),
        10004 => Some("data/sprite/몬스터/DEVIRUCHI_젖꼭지.act"),
        10005 => Some("data/sprite/몬스터/DOKEBI_아후로머리.act"),
        10006 => Some("data/sprite/몬스터/isis_클레오파트라머리띠.act"),
        10007 => Some("data/sprite/몬스터/lunatic_리본.act"),
        10008 => Some("data/sprite/몬스터/munak_요술봉.act"),
        10009 => Some("data/sprite/몬스터/ork_warrior_꽃.act"),
        10010 => Some("data/sprite/몬스터/pecopeco_냄비.act"),
        10011 => Some("data/sprite/몬스터/PETIT_별.act"),
        10012 => Some("data/sprite/몬스터/picky_알껍질.act"),
        10013 => Some("data/sprite/몬스터/poring_책가방.act"),
        10014 => Some("data/sprite/몬스터/rocker_메뚜기안경.act"),
        10015 => Some("data/sprite/몬스터/savage_babe_레이스.act"),
        10016 => Some("data/sprite/몬스터/SOHEE_방울.act"),
        10017 => Some("data/sprite/몬스터/spore_원주민치마.act"),
        10018 => Some("data/sprite/몬스터/yoyo_머리띠.act"),
        10019 => Some("data/sprite/몬스터/smokie_머플러.act"),
        10020 => Some("data/sprite/몬스터/bon_gun_영환도사검.act"),
        10021 => Some("data/sprite/몬스터/BACSOJIN_동그란머리장식.act"),
        10022 => Some("data/sprite/몬스터/CIVIL_SERVANT_금빛귀걸이.act"),
        10023 => Some("data/sprite/몬스터/LEAF_CAT_초록복주머니.act"),
        10024 => Some("data/sprite/몬스터/LOLI_RURI_패션안경.act"),
        10025 => Some("data/sprite/몬스터/MARIONETTE_별모양머리띠.act"),
        10026 => Some("data/sprite/몬스터/SHINOBI_두루마기용술.act"),
        10027 => Some("data/sprite/몬스터/WHISPER_영혼고리_.act"),
        10028 => Some("data/sprite/몬스터/GOBLIN_LEADER_멋진휘장.act"),
        10029 => Some("data/sprite/몬스터/WICKED_NYMPH_옥노리개.act"),
        10030 => Some("data/sprite/몬스터/MIYABI_NINGYO_여름부채.act"),
        10031 => Some("data/sprite/몬스터/DULLAHAN_죽음의고리.act"),
        10032 => Some("data/sprite/몬스터/MEDUSA_여왕의코로넷.act"),
        10033 => Some("data/sprite/몬스터/STONE_SHOOTER_아프로헤어.act"),
        10034 => Some("data/sprite/몬스터/INCUBUS_무도회가면.act"),
        10035 => Some("data/sprite/몬스터/GOLEM_태엽.act"),
        10036 => Some("data/sprite/몬스터/NIGHTMARE_TERROR_지옥의뿔.act"),
        10037 => Some("data/sprite/몬스터/SUCCUBUS_검은나비가면.act"),
        10038 => Some("data/sprite/몬스터/IMP_뿔보호대.act"),
        _ => None,
    }
}
/// Pet emotion table [hunger 0-4][friendly 0-4][act 0-6] -> emotion id (ported).
/// -1 means no emote for that combination.
pub fn pet_emotion(hunger: usize, friendly: usize, act: usize) -> Option<u16> {
    const T: [[[i16; 7]; 5]; 5] = [
        [
            [32, 32, 29, 29, 7, 23, 28],
            [32, 32, 29, 29, 7, 7, 5],
            [20, 32, -1, 32, 5, 20, 10],
            [33, -1, -1, 10, 20, 10, 6],
            [18, -1, -1, 20, 33, 2, 6],
        ],
        [
            [20, 32, 29, 29, 32, 32, 5],
            [20, 32, -1, 32, 29, 32, 32],
            [33, -1, -1, 10, 20, 10, 6],
            [18, -1, -1, 20, 33, 2, 6],
            [15, -1, -1, 19, 3, 2, 21],
        ],
        [
            [32, 32, -1, 32, 29, 5, 32],
            [20, -1, -1, 10, 10, 10, 20],
            [33, -1, -1, 20, 33, 2, 6],
            [18, -1, -1, 19, 18, 2, 21],
            [15, 21, -1, 23, 4, 33, 21],
        ],
        [
            [32, -1, -1, 10, 10, 10, 20],
            [32, -1, -1, 20, 20, 20, 10],
            [20, -1, -1, 19, 21, 2, 6],
            [33, 21, 19, 23, 3, 33, 21],
            [18, 21, 26, 28, 30, 22, 18],
        ],
        [
            [23, -1, -1, 20, 20, 20, 9],
            [32, -1, -1, 19, 20, 0, 0],
            [32, 21, 19, 23, 18, 33, 21],
            [20, 21, 26, 28, 3, 18, 18],
            [20, 21, 26, 28, 30, 18, 30],
        ],
    ];
    let v = *T.get(hunger)?.get(friendly)?.get(act)?;
    (v >= 0).then_some(v as u16)
}
